/* tslint:disable */

/**
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetLockedSubscriptionPreviewResponseInner
 */
export interface GetLockedSubscriptionPreviewResponseInner {
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    rewardAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    totalRewardAmt?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    extraRewardAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    estTotalExtraRewardAmt?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    boostRewardAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    estDailyRewardAmt?: string;
    /**
     *
     * @type {string}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    nextPay?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    nextPayDate?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    valueDate?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    rewardsEndDate?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    deliverDate?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLockedSubscriptionPreviewResponseInner
     */
    nextSubscriptionDate?: number | bigint;
}
