/* tslint:disable */

/**
 * Spot WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AvgPriceResponse
 */
export interface AvgPriceResponse {
    /**
     * Event type
     * @type {string}
     * @memberof AvgPriceResponse
     */
    e?: string;
    /**
     * Event time
     * @type {number | bigint}
     * @memberof AvgPriceResponse
     */
    E?: number | bigint;
    /**
     * Symbol
     * @type {string}
     * @memberof AvgPriceResponse
     */
    s?: string;
    /**
     * Average price interval
     * @type {string}
     * @memberof AvgPriceResponse
     */
    i?: string;
    /**
     * Average price
     * @type {string}
     * @memberof AvgPriceResponse
     */
    w?: string;
    /**
     * Last trade time
     * @type {number | bigint}
     * @memberof AvgPriceResponse
     */
    T?: number | bigint;
}
