/* tslint:disable */

/**
 * Spot WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DiffBookDepthResponse
 */
export interface DiffBookDepthResponse {
    /**
     * Event type
     * @type {string}
     * @memberof DiffBookDepthResponse
     */
    e?: string;
    /**
     * Event time
     * @type {number | bigint}
     * @memberof DiffBookDepthResponse
     */
    E?: number | bigint;
    /**
     * Symbol
     * @type {string}
     * @memberof DiffBookDepthResponse
     */
    s?: string;
    /**
     * First update ID in event
     * @type {number | bigint}
     * @memberof DiffBookDepthResponse
     */
    U?: number | bigint;
    /**
     * Final update ID in event
     * @type {number | bigint}
     * @memberof DiffBookDepthResponse
     */
    u?: number | bigint;
    /**
     * Bids to be updated
     * @type {Array<Array<string>>}
     * @memberof DiffBookDepthResponse
     */
    b?: Array<Array<string>>;
    /**
     * Asks to be updated
     * @type {Array<Array<string>>}
     * @memberof DiffBookDepthResponse
     */
    a?: Array<Array<string>>;
}
