/* tslint:disable */
/* eslint-disable */
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Spot WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BalanceUpdate } from './balance-update';
// May contain unused imports in some cases
// @ts-ignore
import type { EventStreamTerminated } from './event-stream-terminated';
// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionReport } from './execution-report';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalLockUpdate } from './external-lock-update';
// May contain unused imports in some cases
// @ts-ignore
import type { ListStatus } from './list-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ListStatusOInner } from './list-status-oinner';
// May contain unused imports in some cases
// @ts-ignore
import type { OutboundAccountPosition } from './outbound-account-position';
// May contain unused imports in some cases
// @ts-ignore
import type { OutboundAccountPositionBInner } from './outbound-account-position-binner';

/**
 * @type UserDataStreamEventsResponse
 */
export type UserDataStreamEventsResponse =
    | ({ e: 'balanceUpdate' } & BalanceUpdate)
    | ({ e: 'eventStreamTerminated' } & EventStreamTerminated)
    | ({ e: 'executionReport' } & ExecutionReport)
    | ({ e: 'externalLockUpdate' } & ExternalLockUpdate)
    | ({ e: 'listStatus' } & ListStatus)
    | ({ e: 'outboundAccountPosition' } & OutboundAccountPosition);
