/* tslint:disable */
/* eslint-disable */

/**
 * Futures (COIN-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ContinuousContractKlineCandlestickStreamsResponseK } from './continuous-contract-kline-candlestick-streams-response-k';

/**
 *
 * @export
 * @interface ContinuousContractKlineCandlestickStreamsResponse
 */
export interface ContinuousContractKlineCandlestickStreamsResponse {
    /**
     * eventType
     * @type {string}
     * @memberof ContinuousContractKlineCandlestickStreamsResponse
     */
    e?: string;
    /**
     * eventTime
     * @type {number | bigint}
     * @memberof ContinuousContractKlineCandlestickStreamsResponse
     */
    E?: number | bigint;
    /**
     * Pair
     * @type {string}
     * @memberof ContinuousContractKlineCandlestickStreamsResponse
     */
    ps?: string;
    /**
     * Contract type
     * @type {string}
     * @memberof ContinuousContractKlineCandlestickStreamsResponse
     */
    ct?: string;
    /**
     *
     * @type {ContinuousContractKlineCandlestickStreamsResponseK}
     * @memberof ContinuousContractKlineCandlestickStreamsResponse
     */
    k?: ContinuousContractKlineCandlestickStreamsResponseK;
}
