/* tslint:disable */
/* eslint-disable */

/**
 * Futures (COIN-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderTradeUpdateO } from './order-trade-update-o';

/**
 *
 * @export
 * @interface OrderTradeUpdate
 */
export interface OrderTradeUpdate {
    /**
     * Event Time
     * @type {number | bigint}
     * @memberof OrderTradeUpdate
     */
    E?: number | bigint;
    /**
     * Transaction Time
     * @type {number | bigint}
     * @memberof OrderTradeUpdate
     */
    T?: number | bigint;
    /**
     * Account Alias
     * @type {string}
     * @memberof OrderTradeUpdate
     */
    i?: string;
    /**
     *
     * @type {OrderTradeUpdateO}
     * @memberof OrderTradeUpdate
     */
    o?: OrderTradeUpdateO;
}
