/* tslint:disable */

/**
 * Binance VIP Loan REST API
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryVIPLoanFixedRateMarketResponseRowsInner
 */
export interface QueryVIPLoanFixedRateMarketResponseRowsInner {
    /**
     *
     * @type {number | bigint}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    requestId?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    requestNo?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    coin?: string;
    /**
     *
     * @type {string}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    interestRate?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    duration?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    minimumAmount?: string;
    /**
     *
     * @type {string}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    availableAmount?: string;
    /**
     *
     * @type {string}
     * @memberof QueryVIPLoanFixedRateMarketResponseRowsInner
     */
    estimatedInterest?: string;
}
