/* tslint:disable */
/* eslint-disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInformationResponseAssetsInner } from './exchange-information-response-assets-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInformationResponseRateLimitsInner } from './exchange-information-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInformationResponseSymbolsInner } from './exchange-information-response-symbols-inner';

/**
 *
 * @export
 * @interface ExchangeInformationResponse
 */
export interface ExchangeInformationResponse {
    /**
     *
     * @type {Array<string>}
     * @memberof ExchangeInformationResponse
     */
    exchangeFilters?: Array<string>;
    /**
     * Rate Limits.
     * @type {Array<ExchangeInformationResponseRateLimitsInner>}
     * @memberof ExchangeInformationResponse
     */
    rateLimits?: Array<ExchangeInformationResponseRateLimitsInner>;
    /**
     * Ignore please. If you want to check current server time, please check via \"GET /fapi/v1/time\"
     * @type {number | bigint}
     * @memberof ExchangeInformationResponse
     */
    serverTime?: number | bigint;
    /**
     * assets information
     * @type {Array<ExchangeInformationResponseAssetsInner>}
     * @memberof ExchangeInformationResponse
     */
    assets?: Array<ExchangeInformationResponseAssetsInner>;
    /**
     * Symbols.
     * @type {Array<ExchangeInformationResponseSymbolsInner>}
     * @memberof ExchangeInformationResponse
     */
    symbols?: Array<ExchangeInformationResponseSymbolsInner>;
    /**
     * Timezone.
     * @type {string}
     * @memberof ExchangeInformationResponse
     */
    timezone?: string;
}
