/* tslint:disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetDownloadIdForFuturesOrderHistoryResponse
 */
export interface GetDownloadIdForFuturesOrderHistoryResponse {
    /**
     * Average time taken for data download in the past 30 days
     * @type {number | bigint}
     * @memberof GetDownloadIdForFuturesOrderHistoryResponse
     */
    avgCostTimestampOfLast30d?: number | bigint;
    /**
     * Download Id.
     * @type {string}
     * @memberof GetDownloadIdForFuturesOrderHistoryResponse
     */
    downloadId?: string;
}
