/* tslint:disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetFuturesOrderHistoryDownloadLinkByIdResponse
 */
export interface GetFuturesOrderHistoryDownloadLinkByIdResponse {
    /**
     * Download Id.
     * @type {string}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    downloadId?: string;
    /**
     * Enum：completed，processing
     * @type {string}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    status?: string;
    /**
     * The link is mapped to download id
     * @type {string}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    url?: string;
    /**
     * ignore
     * @type {boolean}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    notified?: boolean;
    /**
     * The link would expire after this timestamp
     * @type {number | bigint}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    expirationTimestamp?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof GetFuturesOrderHistoryDownloadLinkByIdResponse
     */
    isExpired?: string;
}
