/* tslint:disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NewOrderResponse
 */
export interface NewOrderResponse {
    /**
     * Client Order Id.
     * @type {string}
     * @memberof NewOrderResponse
     */
    clientOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof NewOrderResponse
     */
    cumQty?: string;
    /**
     * Executed Qty.
     * @type {string}
     * @memberof NewOrderResponse
     */
    executedQty?: string;
    /**
     * Order Id.
     * @type {number | bigint}
     * @memberof NewOrderResponse
     */
    orderId?: number | bigint;
    /**
     * Orig Qty.
     * @type {string}
     * @memberof NewOrderResponse
     */
    origQty?: string;
    /**
     * Price.
     * @type {string}
     * @memberof NewOrderResponse
     */
    price?: string;
    /**
     * Reduce Only.
     * @type {boolean}
     * @memberof NewOrderResponse
     */
    reduceOnly?: boolean;
    /**
     * Side.
     * @type {string}
     * @memberof NewOrderResponse
     */
    side?: string;
    /**
     * Position Side.
     * @type {string}
     * @memberof NewOrderResponse
     */
    positionSide?: string;
    /**
     * Status.
     * @type {string}
     * @memberof NewOrderResponse
     */
    status?: string;
    /**
     * ignored for LIMIT / MARKET orders
     * @type {string}
     * @memberof NewOrderResponse
     */
    stopPrice?: string;
    /**
     * if Close-All
     * @type {boolean}
     * @memberof NewOrderResponse
     */
    closePosition?: boolean;
    /**
     * Symbol.
     * @type {string}
     * @memberof NewOrderResponse
     */
    symbol?: string;
    /**
     * Time In Force.
     * @type {string}
     * @memberof NewOrderResponse
     */
    timeInForce?: string;
    /**
     * Type.
     * @type {string}
     * @memberof NewOrderResponse
     */
    type?: string;
    /**
     * Orig Type.
     * @type {string}
     * @memberof NewOrderResponse
     */
    origType?: string;
    /**
     * Update Time.
     * @type {number | bigint}
     * @memberof NewOrderResponse
     */
    updateTime?: number | bigint;
    /**
     * Working Type.
     * @type {string}
     * @memberof NewOrderResponse
     */
    workingType?: string;
    /**
     * if conditional order trigger is protected
     * @type {boolean}
     * @memberof NewOrderResponse
     */
    priceProtect?: boolean;
    /**
     * price match mode
     * @type {string}
     * @memberof NewOrderResponse
     */
    priceMatch?: string;
    /**
     * self trading preventation mode
     * @type {string}
     * @memberof NewOrderResponse
     */
    selfTradePreventionMode?: string;
    /**
     * order pre-set auot cancel time for TIF GTD order
     * @type {number | bigint}
     * @memberof NewOrderResponse
     */
    goodTillDate?: number | bigint;
}
