/* tslint:disable */
/* eslint-disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { NotionalAndLeverageBracketsResponse1InnerBracketsInner } from './notional-and-leverage-brackets-response1-inner-brackets-inner';

/**
 *
 * @export
 * @interface NotionalAndLeverageBracketsResponse1Inner
 */
export interface NotionalAndLeverageBracketsResponse1Inner {
    /**
     *
     * @type {string}
     * @memberof NotionalAndLeverageBracketsResponse1Inner
     */
    symbol?: string;
    /**
     * user symbol bracket multiplier, only appears when user\'s symbol bracket is adjusted
     * @type {number}
     * @memberof NotionalAndLeverageBracketsResponse1Inner
     */
    notionalCoef?: number;
    /**
     *
     * @type {Array<NotionalAndLeverageBracketsResponse1InnerBracketsInner>}
     * @memberof NotionalAndLeverageBracketsResponse1Inner
     */
    brackets?: Array<NotionalAndLeverageBracketsResponse1InnerBracketsInner>;
}
