/* tslint:disable */
/* eslint-disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PlaceMultipleOrdersResponseInner } from './place-multiple-orders-response-inner';

/**
 *
 * @export
 * @interface PlaceMultipleOrdersResponse
 */
export interface PlaceMultipleOrdersResponse extends Array<PlaceMultipleOrdersResponseInner> {}
