/* tslint:disable */

/**
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SymbolPriceTickerV2Response1
 */
export interface SymbolPriceTickerV2Response1 {
    /**
     * Symbol.
     * @type {string}
     * @memberof SymbolPriceTickerV2Response1
     */
    symbol?: string;
    /**
     * Price.
     * @type {string}
     * @memberof SymbolPriceTickerV2Response1
     */
    price?: string;
    /**
     * Transaction time
     * @type {number | bigint}
     * @memberof SymbolPriceTickerV2Response1
     */
    time?: number | bigint;
}
