/**
 * Alpha WebSocket Market Streams
 *
 * Access Alpha market streams over WebSocket.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebsocketStreamsBase, WebsocketStream } from '@binance/common';
import { Api } from './modules/api';

import type {
    AggregateTradeStreamRequest,
    AllBookTickerStreamRequest,
    AllMiniTickerStreamRequest,
    AllTickerStreamRequest,
    AllTokens24hTickerStreamRequest,
    BookTickerStreamRequest,
    ContractKlineStreamRequest,
    FullDepthStreamRequest,
    KlineStreamRequest,
    MiniTickerStreamRequest,
    PartialDepthStreamRequest,
    TickerStreamRequest,
    TradeStreamRequest,
} from './modules/api';

import type {
    AggregateTradeStreamResponse,
    AllBookTickerStreamResponse,
    AllMiniTickerStreamResponse,
    AllTickerStreamResponse,
    AllTokens24hTickerStreamResponse,
    BookTickerStreamResponse,
    ContractKlineStreamResponse,
    FullDepthStreamResponse,
    KlineStreamResponse,
    MiniTickerStreamResponse,
    PartialDepthStreamResponse,
    TickerStreamResponse,
    TradeStreamResponse,
} from './types';

export class WebsocketStreamsConnection {
    private websocketBase: WebsocketStreamsBase;
    private api: Api;

    constructor(websocketBase: WebsocketStreamsBase) {
        this.websocketBase = websocketBase;
        this.api = new Api(websocketBase);
    }

    /**
     * Adds an event listener for the specified WebSocket event.
     * @param event - The WebSocket event to listen for, such as 'open', 'message', 'error', 'close', 'ping', or 'pong'.
     * @param listener - The callback function to be executed when the event is triggered. The function can accept any number of arguments.
     */
    on(
        event: 'open' | 'message' | 'error' | 'close' | 'ping' | 'pong',
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        listener: (...args: any[]) => void
    ) {
        this.websocketBase.on(event, listener);
    }

    /**
     * Removes an event listener for the specified WebSocket event.
     * @param event - The WebSocket event to stop listening for, such as 'open', 'message', 'error', 'close', 'ping', or 'pong'.
     * @param listener - The callback function that was previously added as the event listener.
     */
    off(
        event: 'open' | 'message' | 'error' | 'close' | 'ping' | 'pong',
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        listener: (...args: any[]) => void
    ) {
        this.websocketBase.off(event, listener);
    }

    /**
     * Disconnects from the WebSocket server.
     * If there is no active connection, a warning is logged.
     * Otherwise, all connections in the connection pool are closed gracefully,
     * and a message is logged indicating that the connection has been disconnected.
     * @returns A Promise that resolves when all connections have been closed.
     * @throws Error if the WebSocket client is not set.
     */
    disconnect(): Promise<void> {
        return this.websocketBase.disconnect();
    }

    /**
     * Checks if the WebSocket connection is currently open.
     * @returns `true` if the connection is open, `false` otherwise.
     */
    isConnected(): boolean {
        return this.websocketBase.isConnected();
    }

    /**
     * Sends a ping message to all connected Websocket servers in the pool.
     * If no connections are ready, a warning is logged.
     * For each active connection, the ping message is sent, and debug logs provide details.
     * @throws Error if a Websocket client is not set for a connection.
     */
    pingServer(): void {
        this.websocketBase.pingServer();
    }

    /**
     * Subscribes to one or multiple WebSocket streams
     * Handles both single and pool modes
     * @param stream Single stream name or array of stream names to subscribe to
     * @param id Optional subscription ID
     * @returns void
     */
    subscribe(stream: string | string[], id?: string): void {
        this.websocketBase.subscribe(stream, id);
    }

    /**
     * Unsubscribes from one or multiple WebSocket streams
     * Handles both single and pool modes
     * @param stream Single stream name or array of stream names to unsubscribe from
     * @param id Optional unsubscription ID
     * @returns void
     */
    unsubscribe(stream: string | string[], id?: string): void {
        this.websocketBase.unsubscribe(stream, id);
    }

    /**
     * Checks if the WebSocket connection is subscribed to the specified stream.
     * @param stream The name of the WebSocket stream to check.
     * @returns `true` if the connection is subscribed to the stream, `false` otherwise.
     */
    isSubscribed(stream: string): boolean {
        return this.websocketBase.isSubscribed(stream);
    }

    /**
     * Pushes aggregate trade updates for a symbol.
     *
     * @summary Aggregate Trade Stream
     * @param {AggregateTradeStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<AggregateTradeStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#aggregate-trade-stream Binance API Documentation}
     */
    aggregateTradeStream(
        requestParameters: AggregateTradeStreamRequest
    ): WebsocketStream<AggregateTradeStreamResponse> {
        return this.api.aggregateTradeStream(requestParameters);
    }

    /**
     * Pushes best bid/ask updates for all symbols.
     *
     * @summary All Book Ticker Stream
     * @param {AllBookTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<AllBookTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#all-book-ticker-stream Binance API Documentation}
     */
    allBookTickerStream(
        requestParameters: AllBookTickerStreamRequest = {}
    ): WebsocketStream<AllBookTickerStreamResponse> {
        return this.api.allBookTickerStream(requestParameters);
    }

    /**
     * Pushes mini ticker statistics for all symbols.
     *
     * @summary All Mini Ticker Stream
     * @param {AllMiniTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<AllMiniTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#all-mini-ticker-stream Binance API Documentation}
     */
    allMiniTickerStream(
        requestParameters: AllMiniTickerStreamRequest = {}
    ): WebsocketStream<AllMiniTickerStreamResponse> {
        return this.api.allMiniTickerStream(requestParameters);
    }

    /**
     * Pushes full ticker statistics for all symbols.
     *
     * @summary All Ticker Stream
     * @param {AllTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<AllTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#all-ticker-stream Binance API Documentation}
     */
    allTickerStream(
        requestParameters: AllTickerStreamRequest = {}
    ): WebsocketStream<AllTickerStreamResponse> {
        return this.api.allTickerStream(requestParameters);
    }

    /**
     * Pushes 24h ticker-like metrics for all tokens.
     *
     * @summary All Tokens 24h Ticker Stream
     * @param {AllTokens24hTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<AllTokens24hTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#all-tokens24h-ticker-stream Binance API Documentation}
     */
    allTokens24hTickerStream(
        requestParameters: AllTokens24hTickerStreamRequest = {}
    ): WebsocketStream<AllTokens24hTickerStreamResponse> {
        return this.api.allTokens24hTickerStream(requestParameters);
    }

    /**
     * Pushes best bid/ask updates for a symbol.
     *
     * @summary Book Ticker Stream
     * @param {BookTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<BookTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#book-ticker-stream Binance API Documentation}
     */
    bookTickerStream(
        requestParameters: BookTickerStreamRequest
    ): WebsocketStream<BookTickerStreamResponse> {
        return this.api.bookTickerStream(requestParameters);
    }

    /**
     * Pushes kline updates by contractAddress@chainId.
     *
     * @summary Contract Kline Stream
     * @param {ContractKlineStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<ContractKlineStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#contract-kline-stream Binance API Documentation}
     */
    contractKlineStream(
        requestParameters: ContractKlineStreamRequest
    ): WebsocketStream<ContractKlineStreamResponse> {
        return this.api.contractKlineStream(requestParameters);
    }

    /**
     * Returns all available depth, including UI and API orders.
     *
     * @summary Full Depth Stream
     * @param {FullDepthStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<FullDepthStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#full-depth-stream Binance API Documentation}
     */
    fullDepthStream(
        requestParameters: FullDepthStreamRequest
    ): WebsocketStream<FullDepthStreamResponse> {
        return this.api.fullDepthStream(requestParameters);
    }

    /**
     * Pushes kline updates for a symbol.
     *
     * @summary Kline Stream
     * @param {KlineStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<KlineStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#kline-stream Binance API Documentation}
     */
    klineStream(requestParameters: KlineStreamRequest): WebsocketStream<KlineStreamResponse> {
        return this.api.klineStream(requestParameters);
    }

    /**
     * Pushes 24h rolling mini ticker statistics.
     *
     * @summary Mini Ticker Stream
     * @param {MiniTickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<MiniTickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#mini-ticker-stream Binance API Documentation}
     */
    miniTickerStream(
        requestParameters: MiniTickerStreamRequest
    ): WebsocketStream<MiniTickerStreamResponse> {
        return this.api.miniTickerStream(requestParameters);
    }

    /**
     * Pushes partial depth updates (UI orders only).
     *
     * @summary Partial Depth Stream
     * @param {PartialDepthStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<PartialDepthStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#partial-depth-stream Binance API Documentation}
     */
    partialDepthStream(
        requestParameters: PartialDepthStreamRequest
    ): WebsocketStream<PartialDepthStreamResponse> {
        return this.api.partialDepthStream(requestParameters);
    }

    /**
     * Pushes full 24h rolling ticker statistics.
     *
     * @summary Ticker Stream
     * @param {TickerStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<TickerStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#ticker-stream Binance API Documentation}
     */
    tickerStream(requestParameters: TickerStreamRequest): WebsocketStream<TickerStreamResponse> {
        return this.api.tickerStream(requestParameters);
    }

    /**
     * Pushes raw trade updates for a symbol.
     *
     * @summary Trade Stream
     * @param {TradeStreamRequest} requestParameters Request parameters.
     *
     * @returns {WebsocketStream<TradeStreamResponse>}
     * @throws {RequiredError}
     * @see {@link https://developers.binance.com/en/docs/catalog/advanced-trading-alpha-trading/api/ws-streams/~#trade-stream Binance API Documentation}
     */
    tradeStream(requestParameters: TradeStreamRequest): WebsocketStream<TradeStreamResponse> {
        return this.api.tradeStream(requestParameters);
    }
}
