/* tslint:disable */
/* eslint-disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CancelMarginAccountOcoOrdersResponseOrderReportsInner } from './cancel-margin-account-oco-orders-response-order-reports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CancelMarginAccountOcoOrdersResponseOrdersInner } from './cancel-margin-account-oco-orders-response-orders-inner';

/**
 *
 * @export
 * @interface CancelMarginAccountOcoOrdersResponse
 */
export interface CancelMarginAccountOcoOrdersResponse {
    /**
     * Order List ID.
     * @type {number | bigint}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    orderListId?: number | bigint;
    /**
     * Contingency Type.
     * @type {string}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    contingencyType?: string;
    /**
     * List Status Type.
     * @type {string}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    listStatusType?: string;
    /**
     * List Order Status.
     * @type {string}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    listOrderStatus?: string;
    /**
     * List Client Order ID.
     * @type {string}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    listClientOrderId?: string;
    /**
     * Transaction Time.
     * @type {number | bigint}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    transactionTime?: number | bigint;
    /**
     * Trade symbol, if existing.
     * @type {string}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    symbol?: string;
    /**
     * Orders.
     * @type {Array<CancelMarginAccountOcoOrdersResponseOrdersInner>}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    orders?: Array<CancelMarginAccountOcoOrdersResponseOrdersInner>;
    /**
     * Order Reports.
     * @type {Array<CancelMarginAccountOcoOrdersResponseOrderReportsInner>}
     * @memberof CancelMarginAccountOcoOrdersResponse
     */
    orderReports?: Array<CancelMarginAccountOcoOrdersResponseOrderReportsInner>;
}
