/* tslint:disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChangeCmPositionModeResponse
 */
export interface ChangeCmPositionModeResponse {
    /**
     * Code.
     * @type {number | bigint}
     * @memberof ChangeCmPositionModeResponse
     */
    code?: number | bigint;
    /**
     * Msg.
     * @type {string}
     * @memberof ChangeCmPositionModeResponse
     */
    msg?: string;
}
