/* tslint:disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FuturesTradfiPerpsContractResponse
 */
export interface FuturesTradfiPerpsContractResponse {
    /**
     *
     * @type {number}
     * @memberof FuturesTradfiPerpsContractResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof FuturesTradfiPerpsContractResponse
     */
    msg?: string;
}
