/* tslint:disable */
/* eslint-disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryCmModifyOrderHistoryResponseInnerAmendmentOrigQty } from './query-cm-modify-order-history-response-inner-amendment-orig-qty';
// May contain unused imports in some cases
// @ts-ignore
import type { QueryCmModifyOrderHistoryResponseInnerAmendmentPrice } from './query-cm-modify-order-history-response-inner-amendment-price';

/**
 * Amendment.
 * @export
 * @interface QueryCmModifyOrderHistoryResponseInnerAmendment
 */
export interface QueryCmModifyOrderHistoryResponseInnerAmendment {
    /**
     *
     * @type {QueryCmModifyOrderHistoryResponseInnerAmendmentPrice}
     * @memberof QueryCmModifyOrderHistoryResponseInnerAmendment
     */
    price?: QueryCmModifyOrderHistoryResponseInnerAmendmentPrice;
    /**
     *
     * @type {QueryCmModifyOrderHistoryResponseInnerAmendmentOrigQty}
     * @memberof QueryCmModifyOrderHistoryResponseInnerAmendment
     */
    origQty?: QueryCmModifyOrderHistoryResponseInnerAmendmentOrigQty;
    /**
     * Order modification count, representing the number of times the order has been modified
     * @type {number | bigint}
     * @memberof QueryCmModifyOrderHistoryResponseInnerAmendment
     */
    count?: number | bigint;
    /**
     * user-defined modification identifier, only returned if provided in the request
     * @type {number | bigint}
     * @memberof QueryCmModifyOrderHistoryResponseInnerAmendment
     */
    modifyId?: number | bigint;
}
