/* tslint:disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryUmAlgoOrderHistoryResponseInner
 */
export interface QueryUmAlgoOrderHistoryResponseInner {
    /**
     *
     * @type {number | bigint}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    algoId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    clientAlgoId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    algoType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    orderType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    positionSide?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    quantity?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    algoStatus?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    actualOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    actualPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    triggerPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    workingType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    priceMatch?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    closePosition?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    priceProtect?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    reduceOnly?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    createTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    triggerTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryUmAlgoOrderHistoryResponseInner
     */
    goodTillDate?: number | bigint;
}
