/* tslint:disable */
/* eslint-disable */

/**
 * Portfolio Margin REST API
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryUsersMarginForceOrdersResponseRowsInner } from './query-users-margin-force-orders-response-rows-inner';

/**
 *
 * @export
 * @interface QueryUsersMarginForceOrdersResponse
 */
export interface QueryUsersMarginForceOrdersResponse {
    /**
     * Rows.
     * @type {Array<QueryUsersMarginForceOrdersResponseRowsInner>}
     * @memberof QueryUsersMarginForceOrdersResponse
     */
    rows?: Array<QueryUsersMarginForceOrdersResponseRowsInner>;
    /**
     * Total.
     * @type {number | bigint}
     * @memberof QueryUsersMarginForceOrdersResponse
     */
    total?: number | bigint;
}
