/* tslint:disable */

/**
 * Binance Alpha REST API
 *
 * OpenAPI Specification for the Binance Alpha REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetExchangeInfoResponseDataAssetsInner
 */
export interface GetExchangeInfoResponseDataAssetsInner {
    /**
     *
     * @type {string}
     * @memberof GetExchangeInfoResponseDataAssetsInner
     */
    asset?: string;
}
