/* tslint:disable */

/**
 * Alpha Trading REST API
 *
 * APIs for Binance Alpha Trading.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type KlinesResponseDataInnerInner
 */
export type KlinesResponseDataInnerInner = number | string;
