/* tslint:disable */
/* eslint-disable */

/**
 * Alpha Trading REST API
 *
 * APIs for Binance Alpha Trading.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TokenListResponseDataInner } from './token-list-response-data-inner';

/**
 *
 * @export
 * @interface TokenListResponse
 */
export interface TokenListResponse {
    /**
     * API response code. \"000000\" indicates success.
     * @type {string}
     * @memberof TokenListResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof TokenListResponse
     */
    message?: string;
    /**
     * Detailed response message.
     * @type {string}
     * @memberof TokenListResponse
     */
    messageDetail?: string;
    /**
     * Whether request is successful.
     * @type {boolean}
     * @memberof TokenListResponse
     */
    success?: boolean;
    /**
     * List of ALPHA tokens and metadata.
     * @type {Array<TokenListResponseDataInner>}
     * @memberof TokenListResponse
     */
    data?: Array<TokenListResponseDataInner>;
}
