/* tslint:disable */

/**
 * Stocks Trading REST API
 *
 * REST APIs for Binance Stocks Trading. All endpoints under `/sapi/v1/equity/_*`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateRenewListenKeyResponse
 */
export interface CreateRenewListenKeyResponse {
    /**
     * Session identifier for the stock user data stream.
     * @type {string}
     * @memberof CreateRenewListenKeyResponse
     */
    listenKey?: string;
}
