/* tslint:disable */

/**
 * Stocks Trading REST API
 *
 * REST APIs for Binance Stocks Trading. All endpoints under `/sapi/v1/equity/_*`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EquityTradeHistoryResponseRowsInner
 */
export interface EquityTradeHistoryResponseRowsInner {
    /**
     * Execution (per-fill) id.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    executionId?: string;
    /**
     * The owning order\'s id.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    orderId?: string;
    /**
     * US-equity ticker.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    symbol?: string;
    /**
     * Quote asset.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    quote?: string;
    /**
     * `BUY` / `SELL`.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    side?: string;
    /**
     * `MARKET` / `LIMIT`.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    orderType?: string;
    /**
     * Execution price (USD).
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    price?: string;
    /**
     * Executed quantity.
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    qty?: string;
    /**
     * Notional of this execution (`qty × price`).
     * @type {string}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    total?: string;
    /**
     * Execution time (ms epoch).
     * @type {number | bigint}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    executionAt?: number | bigint;
    /**
     * Last update time (ms epoch).
     * @type {number | bigint}
     * @memberof EquityTradeHistoryResponseRowsInner
     */
    updatedAt?: number | bigint;
}
