/* tslint:disable */
/* eslint-disable */

/**
 * Portfolio Margin WebSocket Market Streams
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountUpdateA } from './account-update-a';

/**
 *
 * @export
 * @interface AccountUpdate
 */
export interface AccountUpdate {
    /**
     * Event business unit. \'UM\' for USDS-M futures and \'CM\' for COIN-M futures
     * @type {string}
     * @memberof AccountUpdate
     */
    fs?: string;
    /**
     * Event Time
     * @type {number | bigint}
     * @memberof AccountUpdate
     */
    E?: number | bigint;
    /**
     * Transaction
     * @type {number | bigint}
     * @memberof AccountUpdate
     */
    T?: number | bigint;
    /**
     * Account Alias, ignore for UM
     * @type {string}
     * @memberof AccountUpdate
     */
    i?: string;
    /**
     *
     * @type {AccountUpdateA}
     * @memberof AccountUpdate
     */
    a?: AccountUpdateA;
}
