/**
 * Stocks Trading REST API
 *
 * REST APIs for Binance Stocks Trading. All endpoints under `/sapi/v1/equity/_*`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { jest, expect, beforeEach, describe, it } from '@jest/globals';
import { JSONParse, JSONStringify } from 'json-with-bigint';
import { ConfigurationRestAPI, type RestApiResponse } from '@binance/common';

import {
    TradeApi,
    EquityOrderHistoryOrderTypeEnum,
    EquityOrderHistorySideEnum,
    EquityTradeHistorySideEnum,
    PlaceEquityOrderSideEnum,
    PlaceEquityOrderOrderTypeEnum,
    PlaceEquityOrderTimeInForceEnum,
    PlaceEquityOrderTradingSessionEnum,
    PlaceEquityOrderWalletTypeEnum,
} from '../../../src/rest-api';
import {
    CancelAllEquityOrdersRequest,
    CancelEquityOrderRequest,
    CurrentOpenOrdersRequest,
    EquityOrderDetailRequest,
    EquityOrderHistoryRequest,
    EquityTradeHistoryRequest,
    PlaceEquityOrderRequest,
} from '../../../src/rest-api';
import type {
    CancelAllEquityOrdersResponse,
    CancelEquityOrderResponse,
    CurrentOpenOrdersResponse,
    EquityOrderDetailResponse,
    EquityOrderHistoryResponse,
    EquityTradeHistoryResponse,
    PlaceEquityOrderResponse,
} from '../../../src/rest-api/types';

describe('TradeApi', () => {
    let client: TradeApi;
    let config: ConfigurationRestAPI;
    let mockResponse: object = {};

    beforeEach(() => {
        config = new ConfigurationRestAPI({
            apiKey: 'test-api-key',
            apiSecret: 'test-api-secret',
            basePath: '',
        });
        client = new TradeApi(config);
    });

    describe('cancelAllEquityOrders()', () => {
        it('should execute cancelAllEquityOrders() successfully with required parameters only', async () => {
            mockResponse = JSONParse(JSONStringify({ success: true }));

            const spy = jest.spyOn(client, 'cancelAllEquityOrders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CancelAllEquityOrdersResponse>)
            );
            const response = await client.cancelAllEquityOrders();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute cancelAllEquityOrders() successfully with optional parameters', async () => {
            const params: CancelAllEquityOrdersRequest = {
                recvWindow: 5000,
            };

            mockResponse = JSONParse(JSONStringify({ success: true }));

            const spy = jest.spyOn(client, 'cancelAllEquityOrders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CancelAllEquityOrdersResponse>)
            );
            const response = await client.cancelAllEquityOrders(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest
                .spyOn(client, 'cancelAllEquityOrders')
                .mockRejectedValueOnce(mockError);
            await expect(client.cancelAllEquityOrders()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('cancelEquityOrder()', () => {
        it('should execute cancelEquityOrder() successfully with required parameters only', async () => {
            const params: CancelEquityOrderRequest = {
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
            };

            mockResponse = JSONParse(
                JSONStringify({ orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71', status: 'S' })
            );

            const spy = jest.spyOn(client, 'cancelEquityOrder').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CancelEquityOrderResponse>)
            );
            const response = await client.cancelEquityOrder(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute cancelEquityOrder() successfully with optional parameters', async () => {
            const params: CancelEquityOrderRequest = {
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify({ orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71', status: 'S' })
            );

            const spy = jest.spyOn(client, 'cancelEquityOrder').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CancelEquityOrderResponse>)
            );
            const response = await client.cancelEquityOrder(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when orderId is missing', async () => {
            const _params: CancelEquityOrderRequest = {
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
            };
            const params = Object.assign({ ..._params });
            delete params?.orderId;

            await expect(client.cancelEquityOrder(params)).rejects.toThrow(
                'Required parameter orderId was null or undefined when calling cancelEquityOrder.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: CancelEquityOrderRequest = {
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'cancelEquityOrder').mockRejectedValueOnce(mockError);
            await expect(client.cancelEquityOrder(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('currentOpenOrders()', () => {
        it('should execute currentOpenOrders() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify([
                    {
                        orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                        symbol: 'AAPL',
                        quote: 'USDC',
                        side: 'BUY',
                        orderType: 'LIMIT',
                        limitPrice: '180.50',
                        avgFilledPrice: 'avgFilledPrice',
                        qty: '1',
                        notional: 'notional',
                        filledQty: '0',
                        filledTotal: 'filledTotal',
                        fee: '0',
                        session: 'RTH',
                        status: 'NEW',
                        createdAt: 1735900000000,
                        updatedAt: 1735900000000,
                    },
                ])
            );

            const spy = jest.spyOn(client, 'currentOpenOrders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CurrentOpenOrdersResponse>)
            );
            const response = await client.currentOpenOrders();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute currentOpenOrders() successfully with optional parameters', async () => {
            const params: CurrentOpenOrdersRequest = {
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify([
                    {
                        orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                        symbol: 'AAPL',
                        quote: 'USDC',
                        side: 'BUY',
                        orderType: 'LIMIT',
                        limitPrice: '180.50',
                        avgFilledPrice: 'avgFilledPrice',
                        qty: '1',
                        notional: 'notional',
                        filledQty: '0',
                        filledTotal: 'filledTotal',
                        fee: '0',
                        session: 'RTH',
                        status: 'NEW',
                        createdAt: 1735900000000,
                        updatedAt: 1735900000000,
                    },
                ])
            );

            const spy = jest.spyOn(client, 'currentOpenOrders').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<CurrentOpenOrdersResponse>)
            );
            const response = await client.currentOpenOrders(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'currentOpenOrders').mockRejectedValueOnce(mockError);
            await expect(client.currentOpenOrders()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('equityOrderDetail()', () => {
        it('should execute equityOrderDetail() successfully with required parameters only', async () => {
            mockResponse = JSONParse(
                JSONStringify({
                    orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                    clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                    symbol: 'AAPL',
                    quote: 'USDC',
                    side: 'BUY',
                    orderType: 'LIMIT',
                    limitPrice: '180.50',
                    avgFilledPrice: '180.48',
                    qty: '1',
                    notional: 'notional',
                    filledQty: '1',
                    filledTotal: 'filledTotal',
                    fee: '0.10',
                    session: 'RTH',
                    status: 'FILLED',
                    createdAt: 1735900000000,
                    updatedAt: 1735900120000,
                    trades: [
                        {
                            executionId: 'exec-20260504-0001',
                            executionAt: 1735900115000,
                            price: '180.48',
                            qty: '1',
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityOrderDetail').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityOrderDetailResponse>)
            );
            const response = await client.equityOrderDetail();
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute equityOrderDetail() successfully with optional parameters', async () => {
            const params: EquityOrderDetailRequest = {
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                    clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                    symbol: 'AAPL',
                    quote: 'USDC',
                    side: 'BUY',
                    orderType: 'LIMIT',
                    limitPrice: '180.50',
                    avgFilledPrice: '180.48',
                    qty: '1',
                    notional: 'notional',
                    filledQty: '1',
                    filledTotal: 'filledTotal',
                    fee: '0.10',
                    session: 'RTH',
                    status: 'FILLED',
                    createdAt: 1735900000000,
                    updatedAt: 1735900120000,
                    trades: [
                        {
                            executionId: 'exec-20260504-0001',
                            executionAt: 1735900115000,
                            price: '180.48',
                            qty: '1',
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityOrderDetail').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityOrderDetailResponse>)
            );
            const response = await client.equityOrderDetail(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw an error when server is returning an error', async () => {
            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'equityOrderDetail').mockRejectedValueOnce(mockError);
            await expect(client.equityOrderDetail()).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('equityOrderHistory()', () => {
        it('should execute equityOrderHistory() successfully with required parameters only', async () => {
            const params: EquityOrderHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    total: 2,
                    page: 1,
                    size: 20,
                    rows: [
                        {
                            orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                            symbol: 'AAPL',
                            quote: 'USDC',
                            side: 'BUY',
                            orderType: 'LIMIT',
                            limitPrice: '180.50',
                            avgFilledPrice: '180.48',
                            qty: '1',
                            notional: 'notional',
                            filledQty: '1',
                            filledTotal: 'filledTotal',
                            fee: '0.10',
                            session: 'RTH',
                            status: 'FILLED',
                            createdAt: 1735900000000,
                            updatedAt: 1735900120000,
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityOrderHistory').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityOrderHistoryResponse>)
            );
            const response = await client.equityOrderHistory(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute equityOrderHistory() successfully with optional parameters', async () => {
            const params: EquityOrderHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
                symbol: 'NVDA',
                orderType: EquityOrderHistoryOrderTypeEnum.MARKET,
                side: EquityOrderHistorySideEnum.BUY,
                orderStatus: 'FILLED,CANCELED',
                current: 1,
                size: 20,
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    total: 2,
                    page: 1,
                    size: 20,
                    rows: [
                        {
                            orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                            symbol: 'AAPL',
                            quote: 'USDC',
                            side: 'BUY',
                            orderType: 'LIMIT',
                            limitPrice: '180.50',
                            avgFilledPrice: '180.48',
                            qty: '1',
                            notional: 'notional',
                            filledQty: '1',
                            filledTotal: 'filledTotal',
                            fee: '0.10',
                            session: 'RTH',
                            status: 'FILLED',
                            createdAt: 1735900000000,
                            updatedAt: 1735900120000,
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityOrderHistory').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityOrderHistoryResponse>)
            );
            const response = await client.equityOrderHistory(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when startTime is missing', async () => {
            const _params: EquityOrderHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };
            const params = Object.assign({ ..._params });
            delete params?.startTime;

            await expect(client.equityOrderHistory(params)).rejects.toThrow(
                'Required parameter startTime was null or undefined when calling equityOrderHistory.'
            );
        });

        it('should throw RequiredError when endTime is missing', async () => {
            const _params: EquityOrderHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };
            const params = Object.assign({ ..._params });
            delete params?.endTime;

            await expect(client.equityOrderHistory(params)).rejects.toThrow(
                'Required parameter endTime was null or undefined when calling equityOrderHistory.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: EquityOrderHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'equityOrderHistory').mockRejectedValueOnce(mockError);
            await expect(client.equityOrderHistory(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('equityTradeHistory()', () => {
        it('should execute equityTradeHistory() successfully with required parameters only', async () => {
            const params: EquityTradeHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    total: 1,
                    page: 1,
                    size: 20,
                    rows: [
                        {
                            executionId: 'exec-20260504-0001',
                            orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                            symbol: 'AAPL',
                            quote: 'USDC',
                            side: 'BUY',
                            orderType: 'LIMIT',
                            price: '180.50',
                            qty: '1',
                            total: '180.50',
                            executionAt: 1735900115000,
                            updatedAt: 1735900115200,
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityTradeHistory').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityTradeHistoryResponse>)
            );
            const response = await client.equityTradeHistory(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute equityTradeHistory() successfully with optional parameters', async () => {
            const params: EquityTradeHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
                symbol: 'NVDA',
                side: EquityTradeHistorySideEnum.BUY,
                orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                current: 1,
                size: 20,
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    total: 1,
                    page: 1,
                    size: 20,
                    rows: [
                        {
                            executionId: 'exec-20260504-0001',
                            orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                            symbol: 'AAPL',
                            quote: 'USDC',
                            side: 'BUY',
                            orderType: 'LIMIT',
                            price: '180.50',
                            qty: '1',
                            total: '180.50',
                            executionAt: 1735900115000,
                            updatedAt: 1735900115200,
                        },
                    ],
                })
            );

            const spy = jest.spyOn(client, 'equityTradeHistory').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<EquityTradeHistoryResponse>)
            );
            const response = await client.equityTradeHistory(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when startTime is missing', async () => {
            const _params: EquityTradeHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };
            const params = Object.assign({ ..._params });
            delete params?.startTime;

            await expect(client.equityTradeHistory(params)).rejects.toThrow(
                'Required parameter startTime was null or undefined when calling equityTradeHistory.'
            );
        });

        it('should throw RequiredError when endTime is missing', async () => {
            const _params: EquityTradeHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };
            const params = Object.assign({ ..._params });
            delete params?.endTime;

            await expect(client.equityTradeHistory(params)).rejects.toThrow(
                'Required parameter endTime was null or undefined when calling equityTradeHistory.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: EquityTradeHistoryRequest = {
                startTime: 1735800000000,
                endTime: 1735900000000,
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'equityTradeHistory').mockRejectedValueOnce(mockError);
            await expect(client.equityTradeHistory(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });

    describe('placeEquityOrder()', () => {
        it('should execute placeEquityOrder() successfully with required parameters only', async () => {
            const params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    status: 'S',
                    orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                    clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                })
            );

            const spy = jest.spyOn(client, 'placeEquityOrder').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<PlaceEquityOrderResponse>)
            );
            const response = await client.placeEquityOrder(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should execute placeEquityOrder() successfully with optional parameters', async () => {
            const params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
                quoteAsset: 'USDC',
                price: '180.50',
                quantity: '1',
                notional: '1000.00',
                timeInForce: PlaceEquityOrderTimeInForceEnum.DAY,
                tradingSession: PlaceEquityOrderTradingSessionEnum.RTH,
                walletType: PlaceEquityOrderWalletTypeEnum.CARD,
                clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                tokenize: true,
                recvWindow: 5000,
            };

            mockResponse = JSONParse(
                JSONStringify({
                    status: 'S',
                    orderId: 'c3c58f49-7b0d-4b9e-a2db-1a2f9a3b8c71',
                    clientOrderId: 'web_2c9c92b74f1e4a7c8f3b9e1a2d3c4b5a',
                })
            );

            const spy = jest.spyOn(client, 'placeEquityOrder').mockReturnValue(
                Promise.resolve({
                    data: () => Promise.resolve(mockResponse),
                    status: 200,
                    headers: {},
                    rateLimits: [],
                } as RestApiResponse<PlaceEquityOrderResponse>)
            );
            const response = await client.placeEquityOrder(params);
            expect(response).toBeDefined();
            await expect(response.data()).resolves.toBe(mockResponse);
            spy.mockRestore();
        });

        it('should throw RequiredError when symbol is missing', async () => {
            const _params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
            };
            const params = Object.assign({ ..._params });
            delete params?.symbol;

            await expect(client.placeEquityOrder(params)).rejects.toThrow(
                'Required parameter symbol was null or undefined when calling placeEquityOrder.'
            );
        });

        it('should throw RequiredError when side is missing', async () => {
            const _params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
            };
            const params = Object.assign({ ..._params });
            delete params?.side;

            await expect(client.placeEquityOrder(params)).rejects.toThrow(
                'Required parameter side was null or undefined when calling placeEquityOrder.'
            );
        });

        it('should throw RequiredError when orderType is missing', async () => {
            const _params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
            };
            const params = Object.assign({ ..._params });
            delete params?.orderType;

            await expect(client.placeEquityOrder(params)).rejects.toThrow(
                'Required parameter orderType was null or undefined when calling placeEquityOrder.'
            );
        });

        it('should throw an error when server is returning an error', async () => {
            const params: PlaceEquityOrderRequest = {
                symbol: 'AAPL',
                side: PlaceEquityOrderSideEnum.BUY,
                orderType: PlaceEquityOrderOrderTypeEnum.MARKET,
            };

            const errorResponse = {
                code: -1111,
                msg: 'Server Error',
            };

            const mockError = new Error('ResponseError') as Error & {
                response?: { status: number; data: unknown };
            };
            mockError.response = { status: 400, data: errorResponse };
            const spy = jest.spyOn(client, 'placeEquityOrder').mockRejectedValueOnce(mockError);
            await expect(client.placeEquityOrder(params)).rejects.toThrow('ResponseError');
            spy.mockRestore();
        });
    });
});
