/* tslint:disable */
/* eslint-disable */

/**
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OpenOrdersCancelAllResponseResultInner } from './open-orders-cancel-all-response-result-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PingResponseRateLimitsInner } from './ping-response-rate-limits-inner';

/**
 *
 * @export
 * @interface OpenOrdersCancelAllResponse
 */
export interface OpenOrdersCancelAllResponse {
    /**
     *
     * @type {string}
     * @memberof OpenOrdersCancelAllResponse
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OpenOrdersCancelAllResponse
     */
    status?: number | bigint;
    /**
     *
     * @type {Array<OpenOrdersCancelAllResponseResultInner>}
     * @memberof OpenOrdersCancelAllResponse
     */
    result?: Array<OpenOrdersCancelAllResponseResultInner>;
    /**
     *
     * @type {Array<PingResponseRateLimitsInner>}
     * @memberof OpenOrdersCancelAllResponse
     */
    rateLimits?: Array<PingResponseRateLimitsInner>;
}
