/* tslint:disable */
/* eslint-disable */

/**
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SessionStatusResponseResult } from './session-status-response-result';

/**
 *
 * @export
 * @interface SessionStatusResponse
 */
export interface SessionStatusResponse {
    /**
     *
     * @type {string}
     * @memberof SessionStatusResponse
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof SessionStatusResponse
     */
    status?: number | bigint;
    /**
     *
     * @type {SessionStatusResponseResult}
     * @memberof SessionStatusResponse
     */
    result?: SessionStatusResponseResult;
}
