/* tslint:disable */
/* eslint-disable */

/**
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountCommissionResponseRateLimitsInner } from './account-commission-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { TickerResponse1Result } from './ticker-response1-result';

/**
 *
 * @export
 * @interface TickerResponse1
 */
export interface TickerResponse1 {
    /**
     *
     * @type {string}
     * @memberof TickerResponse1
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TickerResponse1
     */
    status?: number | bigint;
    /**
     *
     * @type {TickerResponse1Result}
     * @memberof TickerResponse1
     */
    result?: TickerResponse1Result;
    /**
     *
     * @type {Array<AccountCommissionResponseRateLimitsInner>}
     * @memberof TickerResponse1
     */
    rateLimits?: Array<AccountCommissionResponseRateLimitsInner>;
}
