/* tslint:disable */

/**
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TickerResponse2RateLimitsInner
 */
export interface TickerResponse2RateLimitsInner {
    /**
     *
     * @type {string}
     * @memberof TickerResponse2RateLimitsInner
     */
    rateLimitType?: string;
    /**
     *
     * @type {string}
     * @memberof TickerResponse2RateLimitsInner
     */
    interval?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TickerResponse2RateLimitsInner
     */
    intervalNum?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof TickerResponse2RateLimitsInner
     */
    limit?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof TickerResponse2RateLimitsInner
     */
    count?: number | bigint;
}
