/* tslint:disable */
/* eslint-disable */

/**
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountCommissionResponseRateLimitsInner } from './account-commission-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { TickerPriceResponse2ResultInner } from './ticker-price-response2-result-inner';

/**
 *
 * @export
 * @interface TickerPriceResponse2
 */
export interface TickerPriceResponse2 {
    /**
     *
     * @type {string}
     * @memberof TickerPriceResponse2
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TickerPriceResponse2
     */
    status?: number | bigint;
    /**
     *
     * @type {Array<TickerPriceResponse2ResultInner>}
     * @memberof TickerPriceResponse2
     */
    result?: Array<TickerPriceResponse2ResultInner>;
    /**
     *
     * @type {Array<AccountCommissionResponseRateLimitsInner>}
     * @memberof TickerPriceResponse2
     */
    rateLimits?: Array<AccountCommissionResponseRateLimitsInner>;
}
