/* tslint:disable */

/**
 * Wallet REST API
 *
 * Query balances, manage assets, and perform wallet operations via the Binance Wallet API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubmitDepositQuestionnaireResponse
 */
export interface SubmitDepositQuestionnaireResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof SubmitDepositQuestionnaireResponse
     */
    trId?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof SubmitDepositQuestionnaireResponse
     */
    accepted?: boolean;
    /**
     *
     * @type {string}
     * @memberof SubmitDepositQuestionnaireResponse
     */
    info?: string;
}
