/* tslint:disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AllOrderListResponseInnerOrdersInner
 */
export interface AllOrderListResponseInnerOrdersInner {
    /**
     *
     * @type {string}
     * @memberof AllOrderListResponseInnerOrdersInner
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AllOrderListResponseInnerOrdersInner
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AllOrderListResponseInnerOrdersInner
     */
    clientOrderId?: string;
}
