/* tslint:disable */
/* eslint-disable */

/**
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionRulesResponseSymbolRulesInnerRulesInner } from './execution-rules-response-symbol-rules-inner-rules-inner';

/**
 *
 * @export
 * @interface ExecutionRulesResponseSymbolRulesInner
 */
export interface ExecutionRulesResponseSymbolRulesInner {
    /**
     *
     * @type {string}
     * @memberof ExecutionRulesResponseSymbolRulesInner
     */
    symbol?: string;
    /**
     *
     * @type {Array<ExecutionRulesResponseSymbolRulesInnerRulesInner>}
     * @memberof ExecutionRulesResponseSymbolRulesInner
     */
    rules?: Array<ExecutionRulesResponseSymbolRulesInnerRulesInner>;
}
