/* tslint:disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MaxNumOrderListsFilter
 */
export interface MaxNumOrderListsFilter {
    /**
     *
     * @type {string}
     * @memberof MaxNumOrderListsFilter
     */
    filterType?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof MaxNumOrderListsFilter
     */
    maxNumOrderLists?: number | bigint;
}
