/* tslint:disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrderCancelReplaceResponseCancelResponse
 */
export interface OrderCancelReplaceResponseCancelResponse {
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    origClientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    orderId?: number | bigint;
    /**
     * Unless it\'s part of an order list, value will be -1
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    clientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    transactTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    origQuoteOrderQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    cummulativeQuoteQty?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    selfTradePreventionMode?: string;
    /**
     * Appears only if the parameter icebergQty was sent in the request.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    icebergQty?: string;
    /**
     * Appears only if the order expired due to STP.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    preventedMatchId?: number | bigint;
    /**
     * Order quantity that expired due to STP.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    preventedQuantity?: string;
    /**
     * Appears for STOP_LOSS, TAKE_PROFIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT orders.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    stopPrice?: string;
    /**
     * Appears only if the strategyId parameter was provided upon order placement.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    strategyId?: number | bigint;
    /**
     * Appears only if the strategyType parameter was provided upon order placement.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    strategyType?: number | bigint;
    /**
     * Delta price change required before order activation.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    trailingDelta?: number | bigint;
    /**
     * Time when the trailing order is now active and tracking price changes.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    trailingTime?: number | bigint;
    /**
     * Field that determines whether order used SOR.
     * @type {boolean}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    usedSor?: boolean;
    /**
     * Determines whether the order is being filled by the SOR or by the order book.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    workingFloor?: string;
    /**
     * Price peg type. Only for pegged orders.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    pegPriceType?: string;
    /**
     * Price peg offset type. Only for pegged orders, if requested.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    pegOffsetType?: string;
    /**
     * Price peg offset value. Only for pegged orders, if requested.
     * @type {number | bigint}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    pegOffsetValue?: number | bigint;
    /**
     * Current price order is pegged at. Only for pegged orders, once determined.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    peggedPrice?: string;
    /**
     * Cause of the order\'s expiration. Appears when an order has expired.
     * @type {string}
     * @memberof OrderCancelReplaceResponseCancelResponse
     */
    expiryReason?: string;
}
