/* tslint:disable */
/* eslint-disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderListOcoResponseOrderReportsInner } from './order-list-oco-response-order-reports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderListOcoResponseOrdersInner } from './order-list-oco-response-orders-inner';

/**
 *
 * @export
 * @interface OrderListOcoResponse
 */
export interface OrderListOcoResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof OrderListOcoResponse
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponse
     */
    contingencyType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponse
     */
    listStatusType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponse
     */
    listOrderStatus?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponse
     */
    listClientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OrderListOcoResponse
     */
    transactionTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderListOcoResponse
     */
    symbol?: string;
    /**
     *
     * @type {Array<OrderListOcoResponseOrdersInner>}
     * @memberof OrderListOcoResponse
     */
    orders?: Array<OrderListOcoResponseOrdersInner>;
    /**
     *
     * @type {Array<OrderListOcoResponseOrderReportsInner>}
     * @memberof OrderListOcoResponse
     */
    orderReports?: Array<OrderListOcoResponseOrderReportsInner>;
}
