/* tslint:disable */
/* eslint-disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderListOpoResponseOrderReportsInner } from './order-list-opo-response-order-reports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderListOpoResponseOrdersInner } from './order-list-opo-response-orders-inner';

/**
 *
 * @export
 * @interface OrderListOpoResponse
 */
export interface OrderListOpoResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof OrderListOpoResponse
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderListOpoResponse
     */
    contingencyType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOpoResponse
     */
    listStatusType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOpoResponse
     */
    listOrderStatus?: string;
    /**
     *
     * @type {string}
     * @memberof OrderListOpoResponse
     */
    listClientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OrderListOpoResponse
     */
    transactionTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderListOpoResponse
     */
    symbol?: string;
    /**
     *
     * @type {Array<OrderListOpoResponseOrdersInner>}
     * @memberof OrderListOpoResponse
     */
    orders?: Array<OrderListOpoResponseOrdersInner>;
    /**
     *
     * @type {Array<OrderListOpoResponseOrderReportsInner>}
     * @memberof OrderListOpoResponse
     */
    orderReports?: Array<OrderListOpoResponseOrderReportsInner>;
}
