/* tslint:disable */
/* eslint-disable */

/**
 * Spot REST API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderOcoResponseOrderReportsInner } from './order-oco-response-order-reports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderOcoResponseOrdersInner } from './order-oco-response-orders-inner';

/**
 *
 * @export
 * @interface OrderOcoResponse
 */
export interface OrderOcoResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof OrderOcoResponse
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderOcoResponse
     */
    contingencyType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderOcoResponse
     */
    listStatusType?: string;
    /**
     *
     * @type {string}
     * @memberof OrderOcoResponse
     */
    listOrderStatus?: string;
    /**
     *
     * @type {string}
     * @memberof OrderOcoResponse
     */
    listClientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof OrderOcoResponse
     */
    transactionTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof OrderOcoResponse
     */
    symbol?: string;
    /**
     *
     * @type {Array<OrderOcoResponseOrdersInner>}
     * @memberof OrderOcoResponse
     */
    orders?: Array<OrderOcoResponseOrdersInner>;
    /**
     *
     * @type {Array<OrderOcoResponseOrderReportsInner>}
     * @memberof OrderOcoResponse
     */
    orderReports?: Array<OrderOcoResponseOrderReportsInner>;
}
