/* tslint:disable */
/* eslint-disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetFuturesPositionRiskOfSubAccountResponseInner } from './get-futures-position-risk-of-sub-account-response-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetFuturesPositionRiskOfSubAccountV2ResponseDeliveryPositionRiskVosInner } from './get-futures-position-risk-of-sub-account-v2-response-delivery-position-risk-vos-inner';

/**
 *
 * @export
 * @interface GetFuturesPositionRiskOfSubAccountV2Response
 */
export interface GetFuturesPositionRiskOfSubAccountV2Response {
    /**
     *
     * @type {Array<GetFuturesPositionRiskOfSubAccountResponseInner>}
     * @memberof GetFuturesPositionRiskOfSubAccountV2Response
     */
    futurePositionRiskVos?: Array<GetFuturesPositionRiskOfSubAccountResponseInner>;
    /**
     *
     * @type {Array<GetFuturesPositionRiskOfSubAccountV2ResponseDeliveryPositionRiskVosInner>}
     * @memberof GetFuturesPositionRiskOfSubAccountV2Response
     */
    deliveryPositionRiskVos?: Array<GetFuturesPositionRiskOfSubAccountV2ResponseDeliveryPositionRiskVosInner>;
}
