/* tslint:disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetSubAccountsStatusOnMarginOrFuturesResponseInner
 */
export interface GetSubAccountsStatusOnMarginOrFuturesResponseInner {
    /**
     *
     * @type {string}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    email?: string;
    /**
     *
     * @type {boolean}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    isSubUserEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    isUserActive?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    insertTime?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    isMarginEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    isFutureEnabled?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof GetSubAccountsStatusOnMarginOrFuturesResponseInner
     */
    mobile?: number | bigint;
}
