/* tslint:disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ModifySubAccountApiKeyPermissionResponse
 */
export interface ModifySubAccountApiKeyPermissionResponse {
    /**
     *
     * @type {string}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    apiName?: string;
    /**
     *
     * @type {string}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    apikey?: string;
    /**
     *
     * @type {boolean}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    canTrade?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    canMarginLoanRepay?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    canFuturesTrade?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    canUniversalTransfer?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    canVanillaOptions?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof ModifySubAccountApiKeyPermissionResponse
     */
    timestamp?: number | bigint;
}
