/* tslint:disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
 */
export interface QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner {
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    borrowed?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    free?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    interest?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    locked?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountSnapshotResponseSnapshotVosInnerDataUserAssetsInner
     */
    netAsset?: string;
}
