/* tslint:disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QuerySubAccountListResponseSubAccountsInner
 */
export interface QuerySubAccountListResponseSubAccountsInner {
    /**
     *
     * @type {number | bigint}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    subUserId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    remark?: string;
    /**
     *
     * @type {boolean}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    isFreeze?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    createTime?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    isManagedSubAccount?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QuerySubAccountListResponseSubAccountsInner
     */
    isAssetManagementSubAccount?: boolean;
}
