/* tslint:disable */

/**
 * Sub Account REST API
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
 */
export interface QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner {
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    fromEmail?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    fromAccountType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    toEmail?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    toAccountType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    amount?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    scheduledData?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    createTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    status?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryManagedSubAccountTransferLogMasterAccountInvestorResponseManagerSubTransferHistoryVosInner
     */
    tranId?: number | bigint;
}
