/* tslint:disable */
/* eslint-disable */

/**
 * Alpha WebSocket Market Streams
 *
 * Access Alpha market streams over WebSocket.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AllTokens24hTickerStreamResponseDInner } from './all-tokens24h-ticker-stream-response-dinner';

/**
 *
 * @export
 * @interface AllTokens24hTickerStreamResponse
 */
export interface AllTokens24hTickerStreamResponse {
    /**
     * Event type
     * @type {string}
     * @memberof AllTokens24hTickerStreamResponse
     */
    e?: string;
    /**
     * Per-token 24-hour ticker metrics
     * @type {Array<AllTokens24hTickerStreamResponseDInner>}
     * @memberof AllTokens24hTickerStreamResponse
     */
    d?: Array<AllTokens24hTickerStreamResponseDInner>;
}
