/* tslint:disable */

/**
 * Futures (USDⓈ-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ListenKeyExpired
 */
export interface ListenKeyExpired {
    /**
     * Event Time
     * @type {number | bigint}
     * @memberof ListenKeyExpired
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof ListenKeyExpired
     */
    listenKey?: string;
}
