/* tslint:disable */
/* eslint-disable */

/**
 * Binance Pay REST API
 *
 * Query Binance Pay transaction history.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetPayTradeHistoryResponseDataInnerReceiverInfoExtend } from './get-pay-trade-history-response-data-inner-receiver-info-extend';

/**
 *
 * @export
 * @interface GetPayTradeHistoryResponseDataInnerReceiverInfo
 */
export interface GetPayTradeHistoryResponseDataInnerReceiverInfo {
    /**
     * Nickname or merchant name.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    name?: string;
    /**
     * Account type: USER for personal, MERCHANT for merchant.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    type?: string;
    /**
     * Email.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    email?: string;
    /**
     * Binance UID.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    binanceId?: string;
    /**
     * Binance Pay ID.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    accountId?: string;
    /**
     * International area code.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    countryCode?: string;
    /**
     * Phone number.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    phoneNumber?: string;
    /**
     * Country code.
     * @type {string}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    mobileCode?: string;
    /**
     *
     * @type {GetPayTradeHistoryResponseDataInnerReceiverInfoExtend}
     * @memberof GetPayTradeHistoryResponseDataInnerReceiverInfo
     */
    extend?: GetPayTradeHistoryResponseDataInnerReceiverInfoExtend;
}
