/* tslint:disable */
/* eslint-disable */

/**
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CrossMarginCollateralRatioResponseInnerCollateralsInner } from './cross-margin-collateral-ratio-response-inner-collaterals-inner';

/**
 *
 * @export
 * @interface CrossMarginCollateralRatioResponseInner
 */
export interface CrossMarginCollateralRatioResponseInner {
    /**
     * collaterals list.
     * @type {Array<CrossMarginCollateralRatioResponseInnerCollateralsInner>}
     * @memberof CrossMarginCollateralRatioResponseInner
     */
    collaterals?: Array<CrossMarginCollateralRatioResponseInnerCollateralsInner>;
    /**
     * asset Names list.
     * @type {Array<string>}
     * @memberof CrossMarginCollateralRatioResponseInner
     */
    assetNames?: Array<string>;
}
