/* tslint:disable */

/**
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetSmallLiabilityExchangeHistoryResponseRowsInner
 */
export interface GetSmallLiabilityExchangeHistoryResponseRowsInner {
    /**
     * asset.
     * @type {string}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    asset?: string;
    /**
     * amount.
     * @type {string}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    amount?: string;
    /**
     * target Asset.
     * @type {string}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    targetAsset?: string;
    /**
     * target Amount.
     * @type {string}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    targetAmount?: string;
    /**
     * biz Type.
     * @type {string}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    bizType?: string;
    /**
     * timestamp.
     * @type {number | bigint}
     * @memberof GetSmallLiabilityExchangeHistoryResponseRowsInner
     */
    timestamp?: number | bigint;
}
