/* tslint:disable */
/* eslint-disable */

/**
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryPreventedMatchesResponseInner } from './query-prevented-matches-response-inner';

/**
 *
 * @export
 * @interface QueryPreventedMatchesResponse
 */
export interface QueryPreventedMatchesResponse extends Array<QueryPreventedMatchesResponseInner> {}
