/* tslint:disable */
/* eslint-disable */

/**
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryMarginAccountsOpenOtootocoOrderListsResponseInnerOrdersInner } from './query-margin-accounts-open-otootoco-order-lists-response-inner-orders-inner';

/**
 *
 * @export
 * @interface QueryMarginAccountsOpenOtootocoOrderListsResponseInner
 */
export interface QueryMarginAccountsOpenOtootocoOrderListsResponseInner {
    /**
     * order List Id.
     * @type {number | bigint}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    orderListId?: number | bigint;
    /**
     * contingency Type.
     * @type {string}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    contingencyType?: string;
    /**
     * list Status Type.
     * @type {string}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    listStatusType?: string;
    /**
     * list Order Status.
     * @type {string}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    listOrderStatus?: string;
    /**
     * list Client Order Id.
     * @type {string}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    listClientOrderId?: string;
    /**
     * transaction Time.
     * @type {number | bigint}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    transactionTime?: number | bigint;
    /**
     * symbol.
     * @type {string}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    symbol?: string;
    /**
     * orders list.
     * @type {Array<QueryMarginAccountsOpenOtootocoOrderListsResponseInnerOrdersInner>}
     * @memberof QueryMarginAccountsOpenOtootocoOrderListsResponseInner
     */
    orders?: Array<QueryMarginAccountsOpenOtootocoOrderListsResponseInnerOrdersInner>;
}
