/* tslint:disable */

/**
 * Options REST API
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExtendBlockTradeOrderResponseLegsInner
 */
export interface ExtendBlockTradeOrderResponseLegsInner {
    /**
     * symbol
     * @type {string}
     * @memberof ExtendBlockTradeOrderResponseLegsInner
     */
    symbol?: string;
    /**
     * side
     * @type {string}
     * @memberof ExtendBlockTradeOrderResponseLegsInner
     */
    side?: string;
    /**
     * quantity
     * @type {string}
     * @memberof ExtendBlockTradeOrderResponseLegsInner
     */
    quantity?: string;
    /**
     * price
     * @type {string}
     * @memberof ExtendBlockTradeOrderResponseLegsInner
     */
    price?: string;
}
