/* tslint:disable */

/**
 * Options REST API
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrderBookResponse
 */
export interface OrderBookResponse {
    /**
     * Bid orders. Each entry is [price, quantity].
     * @type {Array<Array<string>>}
     * @memberof OrderBookResponse
     */
    bids?: Array<Array<string>>;
    /**
     * Ask orders. Each entry is [price, quantity].
     * @type {Array<Array<string>>}
     * @memberof OrderBookResponse
     */
    asks?: Array<Array<string>>;
    /**
     * transaction time
     * @type {number | bigint}
     * @memberof OrderBookResponse
     */
    T?: number | bigint;
    /**
     * update id
     * @type {number | bigint}
     * @memberof OrderBookResponse
     */
    lastUpdateId?: number | bigint;
}
