/* tslint:disable */

/**
 * Options REST API
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SetAutoCancelAllOpenOrdersResponse
 */
export interface SetAutoCancelAllOpenOrdersResponse {
    /**
     * underlying
     * @type {string}
     * @memberof SetAutoCancelAllOpenOrdersResponse
     */
    underlying?: string;
    /**
     * countdown Time
     * @type {number | bigint}
     * @memberof SetAutoCancelAllOpenOrdersResponse
     */
    countdownTime?: number | bigint;
}
