/* tslint:disable */
/* eslint-disable */

/**
 * Margin WebSocket Market Streams
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OutboundAccountPositionBInner } from './outbound-account-position-binner';

/**
 *
 * @export
 * @interface OutboundAccountPosition
 */
export interface OutboundAccountPosition {
    /**
     * Event Time
     * @type {number | bigint}
     * @memberof OutboundAccountPosition
     */
    E?: number | bigint;
    /**
     * Time of last account update
     * @type {number | bigint}
     * @memberof OutboundAccountPosition
     */
    u?: number | bigint;
    /**
     * Balances Array
     * @type {Array<OutboundAccountPositionBInner>}
     * @memberof OutboundAccountPosition
     */
    B?: Array<OutboundAccountPositionBInner>;
}
