/* tslint:disable */
/* eslint-disable */

/**
 * Margin WebSocket Market Streams
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { MarginLevelStatusChange } from './margin-level-status-change';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLiabilityChange } from './user-liability-change';

/**
 * @type RiskDataStreamEventsResponse
 */
export type RiskDataStreamEventsResponse =
    | ({ e: 'MARGIN_LEVEL_STATUS_CHANGE' } & MarginLevelStatusChange)
    | ({ e: 'USER_LIABILITY_CHANGE' } & UserLiabilityChange);
