/* tslint:disable */
/* eslint-disable */
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Margin WebSocket Market Streams
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BalanceUpdate } from './balance-update';
// May contain unused imports in some cases
// @ts-ignore
import type { ExecutionReport } from './execution-report';
// May contain unused imports in some cases
// @ts-ignore
import type { ListStatus } from './list-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ListStatusOInner } from './list-status-oinner';
// May contain unused imports in some cases
// @ts-ignore
import type { ListenKeyExpired } from './listen-key-expired';
// May contain unused imports in some cases
// @ts-ignore
import type { MarginLevelStatusChange } from './margin-level-status-change';
// May contain unused imports in some cases
// @ts-ignore
import type { OutboundAccountPosition } from './outbound-account-position';
// May contain unused imports in some cases
// @ts-ignore
import type { OutboundAccountPositionBInner } from './outbound-account-position-binner';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLiabilityChange } from './user-liability-change';

/**
 * @type TradeDataStreamEventsResponse
 */
export type TradeDataStreamEventsResponse =
    | ({ e: 'MARGIN_LEVEL_STATUS_CHANGE' } & MarginLevelStatusChange)
    | ({ e: 'USER_LIABILITY_CHANGE' } & UserLiabilityChange)
    | ({ e: 'balanceUpdate' } & BalanceUpdate)
    | ({ e: 'executionReport' } & ExecutionReport)
    | ({ e: 'listStatus' } & ListStatus)
    | ({ e: 'listenKeyExpired' } & ListenKeyExpired)
    | ({ e: 'outboundAccountPosition' } & OutboundAccountPosition);
