/* tslint:disable */

/**
 * Crypto Loan REST API
 *
 * Access Binance Crypto Loans to query assets, subscribe to loans, and manage loan positions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetFlexibleLoanAssetsDataResponseRowsInner
 */
export interface GetFlexibleLoanAssetsDataResponseRowsInner {
    /**
     *
     * @type {string}
     * @memberof GetFlexibleLoanAssetsDataResponseRowsInner
     */
    loanCoin?: string;
    /**
     *
     * @type {string}
     * @memberof GetFlexibleLoanAssetsDataResponseRowsInner
     */
    flexibleInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetFlexibleLoanAssetsDataResponseRowsInner
     */
    flexibleMinLimit?: string;
    /**
     *
     * @type {string}
     * @memberof GetFlexibleLoanAssetsDataResponseRowsInner
     */
    flexibleMaxLimit?: string;
}
