/* tslint:disable */
/* eslint-disable */

/**
 * Crypto Loan REST API
 *
 * Access Binance Crypto Loans to query assets, subscribe to loans, and manage loan positions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetFlexibleLoanAssetsDataResponseRowsInner } from './get-flexible-loan-assets-data-response-rows-inner';

/**
 *
 * @export
 * @interface GetFlexibleLoanAssetsDataResponse
 */
export interface GetFlexibleLoanAssetsDataResponse {
    /**
     *
     * @type {Array<GetFlexibleLoanAssetsDataResponseRowsInner>}
     * @memberof GetFlexibleLoanAssetsDataResponse
     */
    rows?: Array<GetFlexibleLoanAssetsDataResponseRowsInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetFlexibleLoanAssetsDataResponse
     */
    total?: number | bigint;
}
