/* tslint:disable */
/* eslint-disable */

/**
 * Futures (USDⓈ-M) WebSocket API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationResponseRateLimitsInner } from './account-information-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { AccountInformationV2ResponseResult } from './account-information-v2-response-result';

/**
 *
 * @export
 * @interface AccountInformationV2Response
 */
export interface AccountInformationV2Response {
    /**
     *
     * @type {string}
     * @memberof AccountInformationV2Response
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountInformationV2Response
     */
    status?: number | bigint;
    /**
     *
     * @type {AccountInformationV2ResponseResult}
     * @memberof AccountInformationV2Response
     */
    result?: AccountInformationV2ResponseResult;
    /**
     *
     * @type {Array<AccountInformationResponseRateLimitsInner>}
     * @memberof AccountInformationV2Response
     */
    rateLimits?: Array<AccountInformationResponseRateLimitsInner>;
}
