/* tslint:disable */

/**
 * Futures (USDⓈ-M) WebSocket API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CancelOrderResponseRateLimitsInner
 */
export interface CancelOrderResponseRateLimitsInner {
    /**
     *
     * @type {string}
     * @memberof CancelOrderResponseRateLimitsInner
     */
    rateLimitType?: string;
    /**
     *
     * @type {string}
     * @memberof CancelOrderResponseRateLimitsInner
     */
    interval?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof CancelOrderResponseRateLimitsInner
     */
    intervalNum?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof CancelOrderResponseRateLimitsInner
     */
    limit?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof CancelOrderResponseRateLimitsInner
     */
    count?: number | bigint;
}
