/* tslint:disable */
/* eslint-disable */
/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Futures (USDⓈ-M) WebSocket API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SymbolOrderBookTickerResponse1 } from './symbol-order-book-ticker-response1';
// May contain unused imports in some cases
// @ts-ignore
import type { SymbolOrderBookTickerResponse1RateLimitsInner } from './symbol-order-book-ticker-response1-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SymbolOrderBookTickerResponse2 } from './symbol-order-book-ticker-response2';
// May contain unused imports in some cases
// @ts-ignore
import type { SymbolOrderBookTickerResponse2ResultInner } from './symbol-order-book-ticker-response2-result-inner';

/**
 * @type SymbolOrderBookTickerResponse
 */
export type SymbolOrderBookTickerResponse =
    | SymbolOrderBookTickerResponse1
    | SymbolOrderBookTickerResponse2;
