/* tslint:disable */
/* eslint-disable */

/**
 * Mining REST API
 *
 * Query mining status, earnings, and account data via the Binance Pool API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { EarningsListResponseDataAccountProfitsInner } from './earnings-list-response-data-account-profits-inner';

/**
 *
 * @export
 * @interface EarningsListResponseData
 */
export interface EarningsListResponseData {
    /**
     *
     * @type {Array<EarningsListResponseDataAccountProfitsInner>}
     * @memberof EarningsListResponseData
     */
    accountProfits?: Array<EarningsListResponseDataAccountProfitsInner>;
    /**
     * Total rows
     * @type {number | bigint}
     * @memberof EarningsListResponseData
     */
    totalNum?: number | bigint;
    /**
     * Rows per page
     * @type {number | bigint}
     * @memberof EarningsListResponseData
     */
    pageSize?: number | bigint;
}
