/* tslint:disable */
/* eslint-disable */

/**
 * Mining REST API
 *
 * Query mining status, earnings, and account data via the Binance Pool API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { HashrateResaleDetailResponseDataProfitTransferDetailsInner } from './hashrate-resale-detail-response-data-profit-transfer-details-inner';

/**
 *
 * @export
 * @interface HashrateResaleDetailResponseData
 */
export interface HashrateResaleDetailResponseData {
    /**
     *
     * @type {Array<HashrateResaleDetailResponseDataProfitTransferDetailsInner>}
     * @memberof HashrateResaleDetailResponseData
     */
    profitTransferDetails?: Array<HashrateResaleDetailResponseDataProfitTransferDetailsInner>;
    /**
     * Total rows
     * @type {number | bigint}
     * @memberof HashrateResaleDetailResponseData
     */
    totalNum?: number | bigint;
    /**
     * Rows per page
     * @type {number | bigint}
     * @memberof HashrateResaleDetailResponseData
     */
    pageSize?: number | bigint;
}
