/* tslint:disable */

/**
 * Mining REST API
 *
 * Query mining status, earnings, and account data via the Binance Pool API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MiningAccountEarningResponseDataAccountProfitsInner
 */
export interface MiningAccountEarningResponseDataAccountProfitsInner {
    /**
     * Time
     * @type {number | bigint}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    time?: number | bigint;
    /**
     * Coin
     * @type {string}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    coinName?: string;
    /**
     * 0: Referral, 1: Refund, 2: Rebate
     * @type {number | bigint}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    type?: number | bigint;
    /**
     * Mining sub-account ID
     * @type {number | bigint}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    puid?: number | bigint;
    /**
     * Mining account
     * @type {string}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    subName?: string;
    /**
     * Amount
     * @type {number}
     * @memberof MiningAccountEarningResponseDataAccountProfitsInner
     */
    amount?: number;
}
