/* tslint:disable */

/**
 * Binance Derivatives Trading Options WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NewSymbolInfoResponse
 */
export interface NewSymbolInfoResponse {
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    e?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof NewSymbolInfoResponse
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    u?: string;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    qa?: string;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    s?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof NewSymbolInfoResponse
     */
    unit?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    mq?: string;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    d?: string;
    /**
     *
     * @type {string}
     * @memberof NewSymbolInfoResponse
     */
    sp?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof NewSymbolInfoResponse
     */
    ed?: number | bigint;
}
